name: tartifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
     - name: checkout the code
       use: actions/checkout@v2
     - name: upload artifact
       use: actions/upload-artifact@v2
       with:
        - name: ${{ ARTIFACT_NAME }}
          path: .
